"""Add metric_id to answers

Revision ID: 998f56365035
Revises: a9831627a378
Create Date: 2024-03-13 13:46:11.563052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998f56365035'
down_revision: Union[str, None] = 'a9831627a378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('metric_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_answers_metric_id_metrics', 'answers', 'metrics', ['metric_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answers_metric_id_metrics', 'answers', type_='foreignkey')
    op.drop_column('answers', 'metric_id')
    # ### end Alembic commands ###
