"""Remove value_options column from metrics table

Revision ID: a0ec5a8f61ac
Revises: 
Create Date: 2024-03-05 11:14:09.248328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ec5a8f61ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'value_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('value_options', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
