"""Add created_at and updated_at columns

Revision ID: a9831627a378
Revises: 5248a87767b0
Create Date: 2024-03-13 12:35:01.455950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9831627a378'
down_revision: Union[str, None] = '5248a87767b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_answers', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    op.add_column('raw_answers', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()))
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    op.add_column('answers', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'updated_at')
    op.drop_column('answers', 'created_at')
    op.drop_column('raw_answers', 'updated_at')
    op.drop_column('raw_answers', 'created_at')
    # ### end Alembic commands ###
